services:
  app:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: app
    restart: always
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    restart: always
    ports:
      - 80:80
    volumes:
      - ./src:/var/www
      - ./nginx:/etc/nginx/conf.d
